Repository Likelion-YeungNam-Univ/13th-StartPoint-was, pull requests merged in 2025-08, with the labels that each got.

#25 [chore/#24]-mysql-setting
  build.gradle
  src/main/resources/application.yml
Labels: Type : Chore

#38 Feat/28 간단분석 상권 유동인구 정보 조회
  build.gradle
  src/main/java/startpointwas/domain/general/controller/FootTrafficController.java
  src/main/java/startpointwas/domain/general/controller/SimpleAnlsController.java
  src/main/java/startpointwas/domain/general/controller/UpjongController.java
  src/main/java/startpointwas/domain/general/dto/FootTrafficDto.java
  src/main/java/startpointwas/domain/general/service/FootTrafficService.java
Labels: Type : Feature, For : API, For : Entity/DB

#54 [feat/#36]-사용자 정보DTO
  src/main/java/startpointwas/domain/user/dto/UserInfoDto.java
Labels: Type : Feature, For : API

#55 [feat/#32]-서비스-회원가입
  src/main/java/startpointwas/domain/user/service/UserService.java
Labels: Type : Feature, For : API

#44 [chore/#39] redis 연결 설정
  src/main/java/startpointwas/domain/practical/config/RedisConfig.java
  src/main/resources/application.yml
Labels: Type : Chore

#47 [chore/45] 간단분석 api 경로 리팩토링
  src/main/java/startpointwas/domain/general/controller/FootTrafficController.java
  src/main/java/startpointwas/domain/general/controller/SimpleAnlsController.java
  src/main/java/startpointwas/domain/general/controller/UpjongController.java
Labels: Type : Chore, For : API

#68 Feat/67 실질분석 동별 업종 데이터 redis 저장
  src/main/java/startpointwas/domain/practical/client/GeneralClient.java
  src/main/java/startpointwas/domain/practical/config/RedisConfig.java
  src/main/java/startpointwas/domain/practical/service/PracticalService.java
Labels: Type : Feature, For : Entity/DB

#69 Feat/15 chat ask api 구현
  build.gradle
  src/main/java/startpointwas/domain/chat/controller/ChatController.java
  src/main/java/startpointwas/domain/chat/dto/ChatRequest.java
  src/main/java/startpointwas/domain/chat/exception/OpenAiApiException.java
  src/main/java/startpointwas/domain/chat/service/ChatContextService.java
Labels: Type : Feature, For : API

#75 [feat/74]동별 업종 데이터 슬림화
  src/main/java/startpointwas/domain/practical/dto/PracticalDongAnlsSlim.java
  src/main/java/startpointwas/domain/practical/mapper/PracticalMapper.java
Labels: Type : Feature, For : Entity/DB

#76 [feat/5]-practical-info-in-openai
  src/main/java/startpointwas/domain/practical/tool/PracticalTools.java
Labels: Type : Feature, For : API

#79 [ANL-PRA-FEAS-04] openai에 전달하는 데이터 전달
  src/main/java/startpointwas/domain/general/dto/SimpleAnlsResponse.java
  src/main/java/startpointwas/domain/practical/controller/FeasibilityController.java
  src/main/java/startpointwas/domain/practical/dto/PracticalDongAnlsSlim.java
  src/main/java/startpointwas/domain/practical/mapper/PracticalMapper.java
  src/main/java/startpointwas/domain/practical/service/PracticalService.java
  src/main/resources/application.yml
Labels: Type : Feature, For : API, For : Entity/DB, Type : AI

#80 [feat/#72]-챗봇컨택스트id 유저id 연동
  src/main/java/startpointwas/domain/chat/controller/ChatController.java
  src/main/java/startpointwas/domain/chat/service/ChatContextService.java
  src/main/java/startpointwas/domain/user/controller/UserController.java
  src/main/java/startpointwas/domain/user/service/UserService.java
  src/main/java/startpointwas/global/SessionConst.java
Labels: Type : Feature, For : API

#86 [ANL-PRA-BENCH-02] 프롬프트 & 응답 스키마 설계
  src/main/java/startpointwas/domain/practical/controller/FeasibilityController.java
  src/main/java/startpointwas/domain/practical/controller/PracticalController.java
  src/main/java/startpointwas/domain/practical/dto/PracticalDongAnls.java
  src/main/java/startpointwas/domain/practical/dto/PracticalDongAnlsSlim.java
  src/main/java/startpointwas/domain/practical/mapper/PracticalMapper.java
  src/main/java/startpointwas/domain/practical/service/PracticalService.java
  src/main/resources/application.yml
Labels: Type : Feature, For : API, For : Entity/DB, Type : AI

#82 [fix/#34]-널 체크 제거
  src/main/java/startpointwas/domain/user/dto/NameRoleRes.java
Labels: Type : Bug, For : API

#84 [fix/#72]-데이터 저장 설정일 감축
  src/main/java/startpointwas/domain/chat/service/ChatContextService.java
Labels: Type : Bug, For : API

#93 [ANL-PRA] 상세분석 계속 요청 보냈을경우 오류 발생
  src/main/java/startpointwas/domain/practical/config/RedisConfig.java
  src/main/java/startpointwas/domain/practical/repository/PracticalRepository.java
  src/main/resources/application.yml
Labels: Type : Bug

#95 [ANL-PRA] 상세분석 파라미터 값을 널로 요청했을 경우 결과가 나옴 버그
  src/main/java/startpointwas/domain/practical/controller/PracticalController.java
Labels: Type : Bug, Type : AI

#113 [Refactor] GitHub Actions, Docker를 이용한 CI/CD 파이프라인 구축
  .github/workflows/gradle.yml
Labels: Type : Chore

#120 [Refactor] CI/CD 파이프라인 브런치 변경
  .github/workflows/gradle.yml
Labels: Type : Chore, Type : Refactor

#110 [ANL-GEN] api 불러오는 general dto 사용하지 않는 데이터 삭제
  src/main/java/startpointwas/domain/general/dto/SimpleAnlsResponse.java
Labels: Type : Chore, For : Entity/DB

#121 [feat/#71]-멘토 정보 불러오는 api
  src/main/java/startpointwas/domain/mentor/component/EntrepreneurDataInitializer.java
  src/main/java/startpointwas/domain/mentor/controller/EntrepreneurViewController.java
  src/main/java/startpointwas/domain/mentor/dto/EntrepreneurViewDto.java
  src/main/java/startpointwas/domain/mentor/dto/UpdateRegistrationTimeRequest.java
  src/main/java/startpointwas/domain/mentor/entity/Entrepreneur.java
  src/main/java/startpointwas/domain/mentor/repository/EntrepreneurRepository.java
Labels: Type : Feature, For : API, For : Entity/DB

#124 [ANL-PRA] (리팩토링) 실질분석 redis 삭제
  src/main/java/startpointwas/domain/practical/config/RedisConfig.java
  src/main/java/startpointwas/domain/practical/controller/PracticalController.java
  src/main/java/startpointwas/domain/practical/repository/PracticalRepository.java
  src/main/java/startpointwas/domain/practical/service/PracticalService.java
  src/main/java/startpointwas/domain/practical/tool/PracticalTools.java
Labels: Type : Refactor, For : Entity/DB

#129 Bug/125 cicd pipeline
  .github/workflows/ci.yml
  Dockerfile
Labels: Type : Chore
